// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"auth465/config"
	"auth465/handler/api"
	"auth465/store"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	userStoreFunc := users.New()
	db, err := provideDatabase(config2)
	if err != nil {
		return application{}, err
	}
	userService := provideUserService(db, userStoreFunc)
	apiApi := api.New(userStoreFunc, userService)
	server := provideServer(config2, apiApi)
	mainApplication := newApplication(server)
	return mainApplication, nil
}
