// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"auth465/config"
	"auth465/handler/api"
	"auth465/store"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	userStore := users.New()
	apiApi := api.New(userStore)
	server := provideServer(config2, apiApi)
	mainApplication := newApplication(server)
	return mainApplication, nil
}
