title = "configuration for local environment"

[database]
host = "postgresql_auth465" # docker network
port = 5432
user = "postgres"
password = "password" # dont write! on production,staging environment. 
dbName = "auth465"
maxIdleConn = 2
MaxOpenConn = 5

 
