title = "configuration for local environment"

[database]
host = "postgresql_auth465" # docker network
port = 5432
user = "postgres"
password = "password" # dont write! on production,staging environment. 
dbName = "auth465"
maxIdleConn = 1
MaxOpenConn = 1

[session]
addr = "redis_auth465:6379"
db = 0

 
